# Објектно ориентирано програмирање
Аудиториски вежби 3
v1.0, 21 Февруари, 2017
include::parts/attributes.adoc[]

:source_dir: ../../src/av3

== Класи

=== Дефинирање класа

.Синтакса
[source,c++]
----
class ime_na_klasata {
private:
/* deklaracija na promenlivi i metodi koi ne se vidlivi nadvor od klasata */
public :
/* deklaracija na promenlivi i metodi koi se vidlivi nadvor od klasata */
};
----

.Пример `oop_av3_ex1.cpp`
[source,c++]
----
include::{source_dir}/oop_av3_ex1.cpp[tags=class]
----

=== Креирање (инстанцирање) објекти

.Синтакса
[source,c++]
----
ime_na_klasa ime_na_objekt;
----

.Пример `oop_av3_ex1.cpp`
[source,c++]
----
include::{source_dir}/oop_av3_ex1.cpp[tags=instance]
----

=== Животен циклус на објектите

- Конструктор (Constructor) - посебен метод на секоја класа кој се повикува секогаш кога се креира (инстанцира) објект од класата
- Деструктор (Destructor) - посебен метод на секоја класа кој се повикува кога треба да се ослободи меморијата која ја опфатил конструираниот објект

== Задачи

=== Триаголник

Да се напише класа за опишување на геометриско тело триаголник. 
Во класата да се напишат методи за пресметување на плоштината и периметарот на триаголникот.

Потоа да се напише главна програма во која ќе се инстнацира еден објект од оваа класа со вредности за страните кои претходно ќе се прочитаат од стандарден влез.
На овој објект да се повикат соодветните методи за пресметување на плоштината и периметарот.

.Решение `oop_av31.cpp`
[source,c++]
----
include::{source_dir}/oop_av31.cpp[]
----

=== Вработен

Да се напише класа во која ќе се чуваат основни податоци за вработен:

- име
- плата
- работна позиција (работната позиција може да биде вработен, директор или шеф).

Напишете главна програма во која се читаат од стандарден влез податоци за N вработени, а потоа се пачати листа на вработените сортирани според висината на платата во опаѓачки редослед.

.Решение `oop_av32.cpp`
[source,c++]
----
include::{source_dir}/oop_av32.cpp[]
----

=== E-mail

Да се напише класа која опишува една e-mail порака. 
Во класата треба да се имплементира метод за прикажување на целокупната порака на екран.
Потоа да се напише главна програма во која се внесуваат параметрите на пораката, се инстанцира објект од оваа класа и се печати на екран неговата содржина. 
За проверување на валидноста на e-mail пораката (постоење на знакот `@` во адресата) да се напише соодветна функција.

.Решение `oop_av33.cpp`
[source,c++]
----
include::{source_dir}/oop_av33.cpp[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av3_src.zip[Source code ZIP]
