# Објектно ориентирано програмирање
Аудиториски вежби 4
include::parts/attributes.adoc[]

:source_dir: ../../src/av4

== Композиција, copy-конструктор

=== Средба

Да се дефинира класа `Momche` која содржи информации за име, презиме и години. За класата да се дефинираат конструктори, деструктор и метод за печатење на објектот на екран во формат:

`Momche: Ime Prezime Godini`.

Да се дефинира класа `Devojche` со истите атрибути и методи со разлика во форматот на печатење:
 
`Devojche: Ime prezime godini`. 

Креирајте класа `Sredba` која содржи податоци за едно момче и едно девојче. 

- Креирајте функција `print`() која ги печати податоците за момчето и девојчето во следниот формат:

`Sredba: Momche: Ime Prezime Godini Devojche: Ime Prezime Godini`.
 
- Напишете функција `daliSiOdgovaraat`() која печати "Si odgovaraat" доколку разликата на нивните години е помала или еднаква на 5 или "Ne si odgovaraat" во спротивно.

.Решение `oop_av41.cpp`
[source,cpp]
----
include::{source_dir}/oop_av41.cpp[]
----

=== Екипа

Да се дефинира класа `Ekipa` што содржи информации за име на екипата, година на формирање и градот од каде потекнува. 

Да се дефинира класа `Natprevar` што содржи информации за домаќин, гостин (објекти од класата `Ekipa`), голови кои ги постигнал домаќинот и голови кои ги постигнал гостинот. 

Да се дефинира посебна функција `revans` што како аргументи прима два објекта од класата `Natprevar` и проверува дали едниот натпревар е реванш на другиот. Еден натпревар е реваш на друг ако гостинот и домаќинот од првиот натпревар се истите екипи со домаќинот и гостинот од вториот натпревар, соодветно. 

Да се дефинира функцијата `duel` која што како аргументи прима два објекта од класата `Natprevar` и ако едниот натпревар е ревашн на другиот функцијата треба да ја врати екипата која е подобра во меѓусебниот дуел. Во спротивно да испечати порака дека натпреварите не се совпаѓаат. 
Во случајот кога е нерешено функцијата враќа 0.

.Решение `oop_av42.cpp`
[source,cpp]
----
include::{source_dir}/oop_av42.cpp[]
----

=== Вработен

Да се напише класа `Datum` во која ќе се чуваат ден, месец и година (цели броеви). 

Да се напише класа `Vraboten` во која се чува име на вработениот (не повеќе од 20 знаци), плата и датум на раѓање (објект од класата `Datum`). 

Да се напишат две функции кои како аргументи примаат низа од вработени и големина на низата. 
Едната функција го враќа вработениот со најголема плата, а другата функција го враќа најмладиот вработен во фирмата. 

Во главната програма потребно е да се испечатат на екран податоците за најмалдиот и најплатениот вработен. 
Печатењето на вработениот да биде реализирано со посебна функција `print()` во рамките на класата `Vraboten`.

.Решение `oop_av43.cpp`
[source,cpp]
----
include::{source_dir}/oop_av43.cpp[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av4_src.zip[Source code ZIP]
