# Објектно ориентирано програмирање
Аудиториски вежби 5
v1.0, 27 Февруари, 2017
include::parts/attributes.adoc[]

:source_dir: ../../src/av5

== Пријателски функции, динамичка алокација на меморија 

=== Пример 1

Да се дефинира класа `Ekipa` што содржи информации за име на екипата, назив на стадионот на кој игра и градот од каде потекнува. 

Во главната програма да се креираат два покажувачи кон објект 
од класата `Ekipa`. Потоа отпечати ги информациите за креираните објекти.
 
.Решение `oop_av51a.cpp`
[source,cpp]
----
include::{source_dir}/oop_av51a.cpp[]
----

=== Пример 2

Да се дефинира класа `Ekipa` што содржи информации за име на екипата, назив на стадионот на кој игра и градот од каде потекнува. 

Да се дефинира класа `Natprevar` што содржи информации за домаќин, гостин (покажувачи кон објекти од класата `Ekipa`), голови кои ги постигнал домаќинот и голови кои ги постигнал гостинот. 

Да се дефинира глобална функција `isTip` која како аргумент добива еден објект од класата `Natprevar` и тип за натпреварот (еден знак: 1,2 или X) и враќа дали дадениот тип е точен за натпреварот. 

Во главната програма да се креира објект од класата Natprevar и да се провери дали типот 1 е точен тип за креираниот натпревар.
 
.Решение `oop_av51b.cpp`
[source,cpp]
----
include::{source_dir}/oop_av51b.cpp[]
----

=== Пример 3
Да се дефинира класа `Ekipa` што содржи информации за име на екипата, назив на стадионот на кој игра и градот од каде потекнува. 

Во главната програма да се креира покажувач кон динамичко алоцирано поле од објекти кон класата `Ekipa`. Да се внесат N екипи од тастатура, да се сортираат по име и да се прикажат на екран.
 
.Решение `oop_av51c.cpp`
[source,cpp]
----
include::{source_dir}/oop_av51c.cpp[]
----

== Задачи

=== Array
Да се напише класа `Array` за работа со еднодимензионални полиња од целоброjни елементи. За полето се чуваат информации  за неговиот вкупен капцитет, тековниот броj на елементи. 
Резервациjата на мемориjата да се врши динамички.
Во класата да се имплементираат следните функции:

- `add` за додавање нови броеви во полето и притоа ако е исполнет капацитетот на полето (низата) да се зголеми  за 100%.
- `change` која има два целобројни аргументи А и В и ги заменува сите броеви А од полето во В.
- `deleteAll` која ги брише сите појавувања на целоброниот аргумент во полето, а притоа капацитетот да не се промени. 
- `print` за печатење на елементите од полето.

Да се тестира класата во main функција.

.Решение `oop_av52.cpp`
[source,cpp]
----
include::{source_dir}/oop_av52.cpp[]
----

=== Веб сервери
Да се напише класа за работа со веб сервери (`WebServer`). За секоj веб сервер се чува: неговото име (max 30 знаци) и
- листа од веб страници (динамички алоцирана низа од обjекти од класата `WebPage`).

За секоjа веб страница  се чува: url (max 100 знаци)
и содржина (динмички алоцирана низа од знаци). 

За класата `WebPage` да се имплементираат функциите:

- Функција `daliseIsti` (`WebPage` p) за споредба на веб страници според url

За класата `WebServer` да се имплементираат функциите:

- `addPage`(`WebPage` p) за додавање нова веб страница во серверот ако таа не е во серверот. Во тој случак да се зголеми големината на низата од веб страниците во сервервот за 1.

- `deletePage`(`WebPage` p) за бришење на веб страница од веб серверот ако таа постои. Во тој случај големината на низата од веб страниците треба да се намали за 1.

.Решение `oop_av53.cpp`
[source,cpp]
----
include::{source_dir}/oop_av53.cpp[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av5_src.zip[Source code ZIP]
