# Објектно ориентирано програмирање
Аудиториски вежби 8
include::parts/attributes.adoc[]

:source_dir: ../../src/av8

==  Полиморфизам 

=== Задача

Да се дефинира класа за репрезентација на публикација. За секоја публикација се чуваат информации за годината на издавање (цел број) и за називот на издавачката куќа (низа од знаци).

Од класата публикација да се изведе (public) класа за книга. За секоја книга дополнително треба да се чува и бројот на страници на книгата.

Од класата публикација да се изведе (protected) класа за весник. За весник се чува редниот број на весникот.

Од класата весник да се изведе (private) класа за дневен весник. За секој дневен весник се чува информација за денот и месецот на издавање на весникот. 

Со разни функции да се испита пристапот до податоците и функциите!

.Решение `oop_av81.cpp`
[source,cpp]
----
include::{source_dir}/oop_av81.cpp[]
----

=== Задача
    
Да се дефинира класа за *Хотелска резервација*. За хотелската резервација се чува бројот на денови, бројот на лица, име и презиме на лицето за контакт. Да се земе дека цената на резервацијата за едно лице за еден ден е 25 евра.

Во класата да се дефинира функција `vratiCena()` која враќа колкава е цената на резервацијата. Во класата да се дефинира функција `vratiCena(int uplata)` која враќа колкава цена треба да се врати од касата ако корисникот на резервацијата ја доставува дадената уплата.

Да се изведе класа *Полупансионска хотелска резервација* за резервирање на хотелска соба со појадок. Цената на појадокот за едно лице за еден ден е 5 евра. Да се препокрие соодветно функцијата `vratiCena(int uplata)`.

Да се дефинира класа за Хотел со информации за името на хотелот и салдо на хотелот. Во класата да се дефинира функција `int uplatiZaRezervacija(HotelsaRezervacija &hr, int uplata);` Со оваа функција треба да се направи уплата за дадена хотелска резервација. Ако уплатата ја надминува бараната сума функцијататреба да врати колку пари треба да му се врати на корисникот кој ја прави уплатата. Уплатата треба да се додаде во салдото на хотелот.

*Што ќе се случеше ако аргументот не е референца?*

.Решение `oop_av82.cpp`
[source,cpp]
----
include::{source_dir}/oop_av82.cpp[]
----

=== Задача
    Да се дефинира апстрактна класа за репрезентација на едно геометриско тело. Секое геометриско тело има висина (децимален број) и основа која може да биде различна за различни геометриски фигури.
За апстракната класа да се дефинираат функциите:
- pecati() во која се печатат информациите за телото
- volumen() која ќе го враќа волуменот на телото
- getVisina() која ќе ја враќа висината на телото

  Од класата геометриско тело да се изведе класа за цилиндер, конус и квадар. За еден цилиндер и за еден конус покрај висината се чува и информација за радиусот на основата (децимален број).За квадарот се чуваат информации за страните `а` и `b` на основата (децимални броеви). 
Во `main` функцијата да се декларира и иницизијализра динамички алоцирана низа од покажувачи кон класата која претставува геометриско тело. Од оваа низа:

1. Да се одреди телото со најголем волумен користејќи ја глобалната функција: `void teloSoNajgolemVolumen(GeomTelo *niza[], int n);` Оваа функција треба да ги отпечати информациите за телото од полето предадено како аргумент (`niza` - поле од покажувачи кон `GeomTelo`) кое има најголем волумен.
2. Да се одреди бројот на геометриски тела кои немаат основа круг користејќи ја глобалната функција со потпис: `double getRadius(GeomTelo *g);`. Оваа функција која ќе го враќа радиусот на основата (ако основата на телото е круг), а -1 во спротивно.

.Решение `oop_av83.cpp`
[source,cpp]
----
include::{source_dir}/oop_av83.cpp[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av8_src.zip[Source code ZIP]
