# Објектно ориентирано програмирање
Аудиториски вежби 6
v1.0, 05 март, 2017
include::parts/attributes.adoc[]

:source_dir: ../../src/av6

== Преоптоварување на оператори 

=== Пример 1

Да се напише класа `Array` за работа со еднодимензионални полиња од целобројни елементи. 
За полето се чуваат информации  за неговиот вкупен капцитет, тековниот број на елементи. 
Резервацијата на меморијата да се врши динамички.

Во класата да се преоптоварат следните оператори:

- `+=` за додавање нови броеви во полето и притоа ако е исполнет капацитетот на полето (низата) да се зголеми  за 100%.
- `-=` која ги брише сите појавувања на целоброниот аргумент во полето, а притоа капацитетот да не се промени. 
- `<<` за печатење на елементите од полето.

Да се тестира класата во main функција.
 
.Решение `oop_av61a.cpp`
[source,cpp]
----
include::{source_dir}/oop_av61a.cpp[]
----

=== Пример 2

Да се дополни првиот пример така што ќе се преоптоварат и операторите:
 
- `[]` за пристап до елемент и промена на вредноста на елемент од полето. 
- `==` за споредба на два објекти од класата `Array`. 
  
Да се тестира класата во main функција.
 
.Решение `oop_av61b.cpp`
[source,cpp]
----
include::{source_dir}/oop_av61b.cpp[]
----

== Задачи

=== Комплексен број

Да се дефинира класа за работа со комплексни броеви. За секој комплексен број се чуваат податоци за реалниот и имагинарниот дел. 

Да се преоптоварат операторите +, -, *, /, +=, -=, *=, /= за извршуваање на содветните операции со комплексни броеви.

Да се имплементира операторот << за печатење на комплексен број.

Да се имплементира операторот + за собирање на комплексен и децимален број (како и децимален и комплексен број).

.Решение `oop_av62.cpp`
[source,cpp]
----
include::{source_dir}/oop_av62.cpp[]
----

=== Ученици

Да се напише класа за опис ученици. За секој ученик се чува името (динамички алоцирана низа од знаци), просекот (децимален број) и школска година (цел број). За оваа класа да се имплементираат:

- Конструктори и деструктор
- Оператор `++` за зголемување на запишаната школска година за еден
- Оператор `<<` за печатење на ученик со сите негови податоци
- Оператор `>` за споредување на два ученика според просекот

Потоа треба да се креира класа за опишување на паралелка што содржи динамички алоцирана низа од ученици, како и број на елементи во низата. За оваа класа да се имплементираат:

- Конструктори и деструктор
- Оператор `+=` за додавање на нов студент во паралелката
- Оператор `++` за зголемување на запишаната школска година за еден за сите студенти во низата
- Оператор `<<` за печатење на сите ученици во паралелката
- Метод `nagrada` што ги печати само оние ученици кои имаат просек 10.0.
- Метод `najvisokProsek` што го печати највисокиот просек во паралелката

.Решение `oop_av63.cpp`
[source,cpp]
----
include::{source_dir}/oop_av63.cpp[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av6_src.zip[Source code ZIP]
