# Објектно ориентирано програмирање
Аудиториски вежби 12
v1.0, 8 мај, 2017
include::parts/attributes.adoc[]

:source_dir: ../../src/av12

==  Виртуелен деструктор и задачи за вежбање

=== Виртуелен деструктор

==== Пример 1 – Зошто и кога е потребен виртуелен деструктор?

.Решени без виртуелен деструктор `oop_av121a.cpp`
[source,cpp]
----
include::{source_dir}/oop_av121a.cpp[]
----

.Излез од програмата
----
Konstruiram objekt od Osnovna
Konstruiram objekt od Izvedena
Unishtuvam objekt od Osnovna
----

.Решени со виртуелен деструктор `oop_av121b.cpp`
[source,cpp]
----
include::{source_dir}/oop_av121b.cpp[]
----

.Излез од програмата
----
Konstruiram objekt od Osnovna
Konstruiram objekt od Izvedena
Unishtuvam objekt od Izvedena
Unishtuvam objekt od Osnovna
----

=== Втор колоквиум 2015/2016

==== Задача 1

Издавачката куќа FINKI-Education издава онлајн и печатени книги. 
За секоја книга се чуваат податоци за ISBN бројот (низа од најмногу 20 знаци), насловот (низа од најмногу 50 знаци), авторот (низа од најмногу 30 знаци) и основната цена изразена во $ (реален број). 
Класата за опишување на книгите е апстрактна (5 поени).

За секоја онлајн книга дополнително се чуваат податоци за url од каде може да се симне (динамички резервирана низа од знаци) и големината изразена во MB (цел број). 
За секоја печатена книга дополнително се чуваат податоци за масата изразена во килограми (реален број) и дали ја има на залиха (логичка променлива). (5 поени)

За секој објект од двете изведени класи треба да бидат на располагање следниве методи:

- Метод `bookPrice`, за пресметување на продажната цена на книгата на следниот начин: (10 поени)
   * За онлајн книга - цената се зголемува за 20% од основната цена ако книгата е поголема од 20MB
   * За печатена книга - цената се зголемува за 15% од основната цена ако масата на книгата е поголема од 0.7kg
- Преоптоварен оператор `>` за споредба на две книги од каков било вид според нивната цена. (5 поени)
- Преоптоварен оператор `<<` за печатење на податоците за книгите во формат: (5 поени)
  `[ISBN]: [Наслов], [Автор] [Продажна цена]`

Да се имплементира функција mostExpensiveBook со потпис: `void mostExpensiveBook (Book** books, int n)`
во која се печати вкупниот број на онлајн, односно, печатени книги во проследената низа посебно. (5 поени) Потоа се наоѓа и печати најскапата книга. (5 поени)

Да се обезбедат сите потребни функции за правилно функционирање на програмата. (5 поени)

.Решение `oop_av122.cpp`
[source,cpp]
----
include::{source_dir}/oop_av122.cpp[]
----

=== Задача 2

Да се имплементира класа `Trud` во која се чуваат информации за: (5 поени)

- вид на труд (еден знак и тоа C за конференциски труд, J за труд во списание)
- година на издавање (цел број).

Да се имплементира класа `Student` во која се чува: (5 поени)

- името на студентот (низа од најмногу 30 карактери)
- индекс (цел број)
- година на упис (цел број)
- листа на оцени од положени предмети (низа од цели броеви)
- број на положени предмети (цел број).

За оваа класа да се имплементираат следните методи:

- функција rang() што пресметува просек од положените испити на студентот (5 поени)
- оператор << за печатење на студентот во формат: (5 поени)
  `Индекс Име Година на упис ранг`
  
Да се имплементира класа `PhDStudent` во која покрај основните информации за студентот дополнително се чува: (5 поени):

- листа од објавени трудови (динамички резервирана низа од објекти од класата `Trud`)
- бројот на трудови (цел број).

Во оваа класа да се препокрие соодветно функцијата `rang()` така што на просекот од положените испити ќе се додаде и збирот од поените од објавените трудови на PhD студентот. 
Во зависност од видот на трудот, секој универзитет има посебен начин на бодување на трудовите. 
Начинот на бодување е ист за сите PhD студенти. 
Иницијално да се смета дека конференциски труд се бодува со 1 поен, а труд во списание со 3 поени. 
Универзитетот има можност да ги менува вредностите на бодовите. (5 поени + 5 поени)

За оваа класа да се обезбеди:

- оператор `+=` за додавање нов објект од класата Trud во листата (5 поени). 
Ако се направи обид да се внесе труд што е издаден порано од годината на упис на студентот да се фрли исклучок (објект од класата `Exception`). 
Справувањето со исклучокот треба да се реализира во главната функција main каде што е потребно, но и во конструктор ако е потребно. 
Ако бил генериран исклучок треба да се отпечати соодветна порака за грешка "Ne moze da se vnese dadeniot trud", а новиот труд нема да се внесе во листата на трудови од студентот. (10 поени)

NOTE: Сите променливи на класите се чуваат како приватни.

Да се обезбедат сите потребни функции за правилно функционирање на програмата. (5 поени)

.Решение `oop_av123.cpp`
[source,cpp]
----
include::{source_dir}/oop_av123.cpp[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av12_src.zip[Source code ZIP]
