# Објектно ориентирано програмирање
Аудиториски вежби 7
v1.0, 03 април, 2017
include::parts/attributes.adoc[]

:source_dir: ../../src/av7

==  Наследување 

=== Задача

Да се дефинира класа за репрезентација на тениски играч. За секој тениски играч треба да се чуваат името, презимето како и тоа дали игра во лига (bool).

Од класата тениски играч да се изведе класа за рангиран тениски играч, која ќе репрезентира играч кој игра на меѓународно ниво. За рангираните тениски играчи дополнително треба да се чува и рангот на тенискиот играч.

.Решение `oop_av71.cpp`
[source,cpp]
----
include::{source_dir}/oop_av71.cpp[]
----

=== Задача
Да се дефинира класа DebitAccount за работа со дебитна банкарска сметка. За секоја банкарска сметка треба да се чува име и презиме на корисникот (низа од макс. 100 знаци), број на сметка (long број) и моментално салдо (double). 
Да се овозможат методи за преглед на сметката, депонирање и подигнување на пари од сметката.

Потоа да се дефинира класа CreditAccount што ќе овозможува корисникот на сметката да зема заем од банката. Треба да се овозможи механизам за пресметување на камата доколку корисникот должи пари на банката.
 
.Решение `oop_av72.cpp`
[source,cpp]
----
include::{source_dir}/oop_av72.cpp[]
----
include::parts/footer.adoc[]

link:{sources_zip}/oop_av7_src.zip[Source code ZIP]
