# Object oriented programming
Exercises 1
v1.0, 16 February, 2017
include::parts/attributes_en.adoc[]

:source_dir: ../../src/av1


== Structures

=== Date

Write a program that will compare two dates (day, month, year) and will compute the difference in days between two.
Define a *struct* `date`.

.Solution `oop_av11_en.c`
[source,c]
----
include::{source_dir}/oop_av11_en.c[]
----

=== Vector

Write a program that will compute the vector and scalar product of two vectors.
Vectors are represented with coordinates in three-dimensional coordinate system.
Define a struct `vector`.

.Solution `oop_av12_en.c`
[source,c]
----
include::{source_dir}/oop_av12_en.c[]
----

=== Complex numbers

Write a struct for representing complex numbers. 
Then implement functions for addition, subtraction and multiplication of two complex numbers. 
Test the functions in a main program where you read two complex numbers from standard input.

.Solution `oop_av13_en.c`
[source,c]
----
include::{source_dir}/oop_av13_en.c[]
----

=== Students

Read from standard input data for unknown number of students (not more then 100).
Each row of the data is in following format:

- first name
- last name
- number (format xxyzzzz)
- four numbers (points for each problem)

separated with tab space.

Write a program that will print list of students, where each row will have: last name, first name, number, and total points sorted by the number of points. 
BTW the names should be printed with first capital letter.

.Solution `oop_av14_en.c`
[source,c]
----
include::{source_dir}/oop_av14_en.c[]
----

=== Countries

Write a program that will read from standard input data for countries and will print on the standard output the name of the president of the country whose capital has largest population.

- Data for country: name, president, capital and population.
- Data for city: name and population.
- Data for president: name, political party.

.Solution `oop_av15_en.c`
[source,c]
----
include::{source_dir}/oop_av15_en.c[]
----

include::parts/footer_en.adoc[]

link:{sources_zip}/oop_av1_src_en.zip[Source code ZIP]
