# Објектно ориентирано програмирање
Аудиториски вежби 1
include::parts/attributes.adoc[]

:source_dir: ../../src/av1

== Структури

=== Date

Да се напише програма која ќе споредува два датуми (ден, месец, година) и ќе ја пресмета разликата во денови од едниот до другиот датум. 
Пресметките да се реализираат во посебни функции.
За датумот да се дефинира посебна структура `date`.

.Решение `oop_av11.c`
[source,c]
----
include::{source_dir}/oop_av11.c[]
----

=== Vector

Да се напише програма која ќе го пресметува векторскиот и скаларниот производ на два вектори. 
Векторите се претставени со координати во тродимензионален координатен систем.
Скаларниот и векторскиот производ да се пресметуваат со посебни функции. 
За вектор да се дефинира посебна структура `vector`.

.Решение `oop_av12.c`
[source,c]
----
include::{source_dir}/oop_av12.c[]
----

=== Комплексни броеви

Да се напише програма во која ќе се дефинира структура за претставување комплексни броеви. 
Потоа да се напишат функции за собирање, одземање и множење на два комплексни броја. 
Програмата да се тестира во главна програма во која се вчитуваат два комплексни броја од стандарден влез.

.Решение `oop_av13.c`
[source,c]
----
include::{source_dir}/oop_av13.c[]
----

=== Студенти

Од стандарден влез се читаат податоци за непознат број студенти (не повеќе од 100). 
Податоците се внесуваат така што во секој ред се состои од:

- името
- презимето
- бројот на индекс (формат xxyzzzz)
- четири броја (поени од секоја задача)

со произволен број празни места или табулатори меѓу нив.

Да се напише програма која ќе испечати список на студенти, каде во секој ред ќе има: 
презиме, име, број на индекс, вкупен број на бодови сортиран според бројот на бодови. 
При тоа имињата и презимињата да се напишат со голема почетна буква.

.Решение `oop_av14.c`
[source,c]
----
include::{source_dir}/oop_av14.c[]
----

=== Држави

Да се напише програма која од стандарден влез ќе чита податоци за држави и на екран ќе го отпечати името и презимето на претседателот на државата чиj што главен град има најмногу жители.
Податоци за држава: 

- име
- претседател
- главен град
- број на жители.

Податоци за град: 

- име 
- број на жители.

Податоци за претседател: 

- име  
- презиме
- политичка партија.

.Решение `oop_av15.c`
[source,c]
----
include::{source_dir}/oop_av15.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/oop_av1_src.zip[Source code ZIP]
